
#define RET_SUCCESS_BOOL true

#define RET_HAS_NO_PARAM false

#define RET_NO_TYPE_FOUND false

#define RET_EXCEPTION_BOOL false

#define RET_STD_EXCEPTION -1

#define RET_PARAM_EXCEPTION -1

#define RET_INSUFFICIENT_ARGS -1

#define RET_SUCCESS_INT 0

#define RET_ADDING_EDGE_AGAIN 0

#define RET_NO_LANES_DETECTION 0

#define RET_CANNOT_CALL_OUTPUT_INFO_SERVICE 1

#define RET_FIELD_EMPTY 1

#define RET_WINDOW_SIZE_TOO_SMALL 1

#define RET_NODE_INFO_NULL 1

#define RET_NODE_NAME_WITH_DOT_LAUNCH 1

#define RET_INVALID_PARAM_ENUM_FORMAT 1

#define RET_INVALID_MENU_ITEMS_COUNT 1

#define RET_CANNOT_LOAD_NODES 1

#define RET_UNSUCCESSFUL_FORK 1

#define RET_ROSCORE_FAILED 1

#define RET_ROSLAUNCH_FAILED 1

#define RET_REMOTE_MASTER_SERVICE_FAILED 1

#define RET_NODE_IFACE_SERVICE_FAILED 1

#define RET_NODE_NOT_FOUND 1

#define RET_KILL_NODE_FAILED 1

#define RET_INVALID_MACHINE_NAME 1

#define RET_GRAPH_NODE_OBJECT_DOES_NOT_EXIST 1

#define RET_LAUNCH_NODE_FAIL 1

#define RET_INVALID_BOUNDING_RECT 1

#define RET_NODE_NOT_ON 1

#define RET_RADIO_BUTTON_NAME_EMPTY 1

#define RET_CHECKBOXES_CANNOT_BE_ADDED 1

#define RET_RADIO_BUTTON_ALREADY_EXISTS 1

#define RET_NON_EXISTENT_RADIO_BUTTON_NAME 1

#define RET_IMAGE_NULL 1

#define RET_TEXT_NOT_DRAWN 1

#define RET_INVALID_IMAGE 1

#define RET_VIDEO_CAPTURE_NOT_OPENED 1

#define RET_ADDING_NODE_AGAIN 1

#define RET_INVALID_PATH 1

#define RET_INVALID_FILE 1

#define RET_VIEW_ALREADY_EXISTS 1

#define RET_INVALID_CONTAINER 1

#define RET_VIEW_DOES_NOT_EXIST 1

#define RET_OBJECT_NOT_FOUND 1

#define RET_ERROR_LOADING_FILE 1

#define RET_ERROR_SPLITTING_STRING 1

#define RET_VERTEX_DESCRIPTOR_DOES_NOT_EXIST_FOR_SRC_NODE 1

#define RET_VERTEX_DESCRIPTOR_DOES_NOT_EXIST_FOR_END_NODE 1

#define RET_GRAPH_NODE_OBJECT_DOES_NOT_EXIST_FOR_SRC_NODE 1

#define RET_GRAPH_NODE_OBJECT_DOES_NOT_EXIST_FOR_END_NODE 1

#define RET_ADDING_EDGE_WITH_INVALID_NODES 1

#define RET_INVALID_MATRIX_STREAM_OBJECT 1

#define RET_CANNOT_ADD_DUMMY_EDGE 1

#define RET_CANNOT_REMOVE_DUMMY_EDGE 1

#define RET_CANNOT_OPEN_FILE_INT 1

#define RET_FALSE_VALIDATOR 1

#define RET_PARAM_NOT_FOUND 1

#define RET_TEXT_VIEW_NULL 1

#define RET_EXCEPTION_INT 1

#define RET_PARENT_VIEWNODE_NULL 1

#define RET_INVALID_LANES 1

#define RET_EMPTY_LANES 1

#define RET_LINKING_PARAM_TO_NULL 2

#define RET_CLOSEST_LEGAL_PARAM 2

#define RET_UNLINKING_PARAM_TO_NULL 2

#define RET_OBJECT_PROVIDED_NULL 2

#define RET_PARAM_TYPE_DONOT_MATCH 2

#define RET_INVALID_TYPE 2

#define RET_UNDEFINED_TYPE 3

#define RET_LINK_VAR_SET_NULL 3

#define RET_OUT_OF_BOUND_PARAM 3

#define RET_NEEDED_EXTRA_SUPPORT 4

#define RET_PARAM_MAX_LESS_THAN_MIN 4

#define RET_LINK_VAR_NOT_FOUND 4

#define RET_NEGATIVE_PARAM_INTERVAL 5

#define RET_PARAM_GREATER_THAN_MAX_MIN_DIFF 6

#define RET_SET_PARAM_NOT_FOUND 7
